language: swift
osx_image: xcode9.4
script:
  - xcodebuild clean test -project AppverifyDemo.xcodeproj -scheme Development -destination "platform=iOS Simulator,name=iPhone X,OS=11.0.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
after_success:
  - bash <(curl -s https://codecov.io/bash)
